### ISSUE TITLE
Rendering a date time field always displays sets the time to midnight

### ISSUE THREAD

**Issue by G0dwin** [glebm/to_spreadsheet#27]
I am trying to display a date in the format `d/m/yyyy h:mm` by using number format `22` which seems to be the only number format that renders both date and time as per [Axlsx documentation](https://github.com/randym/axlsx/blob/master/lib/axlsx/stylesheet/num_fmt.rb#L50).

I'm [formatting the string using `strftime("%F %T")`](https://github.com/bikebike/BikeBike/blob/master/app/controllers/conferences_controller.rb#L385) and [setting the `num_fmt` to 22 in the HTML source](https://github.com/bikebike/BikeBike/blob/master/app/views/conferences/stats.xlsx.haml#L18).

After loading the stylesheet the cells are displayed with a `0:00` time, for example the current time would be displayed as `8/11/2016 0:00`. I have tried removing the `num_fmt` and the date and time are displayed correctly, but interpreted as a string by Excel. The result is the same in both MS Excel and OO Calc.

Is this an issue with `to_spreadsheet`, `axslx`, or am I not setting the format correctly?

Thanks!

**Comment by glebm** [comment]
Sounds like what you want is a datetime. Give the `td` element the `datetime` class instead of `date`.

**Comment by G0dwin** [comment]
Interesting, that gives me an exception:

```shell
uninitialized constant ToSpreadsheet::Themes::Default::Chronic
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/themes/default.rb:23:in `block (2 levels) in <module:Default>'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/rule/format.rb:40:in `instance_exec'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/rule/format.rb:40:in `add_and_apply_style'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/rule/format.rb:12:in `block in apply'
/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/selectors.rb:62:in `css_match'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/rule/format.rb:11:in `apply'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/rule/container.rb:15:in `block (2 levels) in apply'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/rule/container.rb:15:in `each'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/rule/container.rb:15:in `block in apply'
(eval):3:in `each'
(eval):3:in `each'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/rule/container.rb:12:in `apply'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/renderer.rb:21:in `block in to_package'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/renderer.rb:19:in `each'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/renderer.rb:19:in `to_package'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/renderer.rb:13:in `to_data'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/rails/action_pack_renderers.rb:21:in `block (2 levels) in <top (required)>'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/context.rb:32:in `call'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/context.rb:32:in `with_context'
/vendor/bundle/ruby/2.2.0/gems/to_spreadsheet-1.0.6/lib/to_spreadsheet/rails/action_pack_renderers.rb:19:in `block in <top (required)>'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each_key'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/rendering.rb:25:in `render'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:16:in `render'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:40:in `render'
/app/controllers/conferences_controller.rb:401:in `block (2 levels) in register'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/mime_responds.rb:216:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/mime_responds.rb:216:in `respond_to'
/app/controllers/conferences_controller.rb:400:in `register'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198:in `process_action'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
/vendor/bundle/ruby/2.2.0/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/profiling_methods.rb:76:in `block in profile_method'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal.rb:195:in `dispatch'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal.rb:236:in `block in action'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:42:in `serve'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `each'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `serve'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802:in `call'
/vendor/bundle/ruby/2.2.0/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call'
/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260:in `call'
/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36:in `call'
/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/vendor/bundle/ruby/2.2.0/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/profiler.rb:171:in `call'
/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
/vendor/bundle/ruby/2.2.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
/vendor/bundle/ruby/2.2.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
/vendor/bundle/ruby/2.2.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/vendor/bundle/ruby/2.2.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
/vendor/bundle/ruby/2.2.0/gems/unicorn-5.1.0/bin/unicorn_rails:209:in `<top (required)>'
/vendor/bundle/ruby/2.2.0/bin/unicorn_rails:23:in `load'
/vendor/bundle/ruby/2.2.0/bin/unicorn_rails:23:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3@global/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.2.3@global/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Completed 500 Internal Server Error in 3852ms
```

It looks like that's happening here: https://github.com/glebm/to_spreadsheet/blob/master/lib/to_spreadsheet/themes/default.rb#L23

**Comment by G0dwin** [comment]
Looks like `default.rb` should include:

```ruby
require 'chronic'
```

**Comment by G0dwin** [comment]
I've tested this in my own branch and it solves the problem. Here is the pull request: https://github.com/glebm/to_spreadsheet/pull/28
